import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/Header";
import { 
  qanelasBlack,
  qanelasBold,
  qanelasExtraBold,
  qanelasMedium,
  qanelasRegular,
  qanelasSemiBold,
  qanelasSemiBoldItalic,
  qanelasRegularItalic
 } from './fonts'
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
          ${qanelasBlack.variable}
          ${qanelasBold.variable}
          ${qanelasMedium.variable}
          ${qanelasRegular.variable}
          ${qanelasSemiBold.variable}
          ${qanelasSemiBoldItalic.variable}
          ${qanelasRegularItalic.variable}
          ${qanelasExtraBold.variable}
        `}>
        <Header />
        {children}
      </body>
    </html>
  );
}
